In [1]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import datetime as datetime

In [2]:
df = pd.read_csv("/Users/rlzhang1310/Coding/BMGT434/by_progression.csv")
df = df[["Competitor", "Mark", "country", "date"]]
df["date"] = pd.to_datetime(df["date"])

/var/folders/r4/sgr1zrxx0038xwsxj6n3k8900000gn/T/ipykernel_95941/793124767.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["date"] = pd.to_datetime(df["date"])

             Competitor    Mark country       date
43                Flack  273.20     AUS 1896-03-30
42           Lermusiaux  250.40     FRA 1896-06-28
41              Bennett  246.20      UK 1900-07-15
40            Lightbody  245.40     USA 1904-09-03
39               Wilson  239.80      UK 1908-05-30
38          Abel KIVIAT  239.20     USA 1912-05-16
37          Abel KIVIAT  235.80     USA 1912-08-06
36          John ZANDER  234.70     SWE 1917-08-05
35          Paavo NURMI  232.60     FIN 1924-06-19
34         Otto PELTZER  231.00     GER 1926-09-11
33     Jules LADOUMÈGUE  229.20     FRA 1930-10-05
32        Luigi BECCALI  229.20     ITA 1933-09-09
31        Luigi BECCALI  229.00     ITA 1933-09-17
30        Bill BONTHRON  228.80     USA 1934-06-30
29        Jack LOVELOCK  227.80     NZL 1936-08-06
28          Gunder HÄGG  227.60     SWE 1941-08-10
27          Gunder HÄGG  225.80     SWE 1942-07-17
26       Arne ANDERSSON  225.00     SWE 1943-08-17
25          Gunder HÄGG  223.00     SWE 1944-07-07
24       Lennart STRAND  223.00     SWE 1947-07-15
23          Werner LUEG  223.00     FRG 1952-06-29
22           Wes SANTEE  222.80     USA 1954-06-04
21           John LANDY  221.80     AUS 1954-06-21
20        Sándor IHAROS  220.80     HUN 1955-07-28
19        László TÁBORI  220.80     HUN 1955-09-06
18       Gunnar NIELSEN  220.80     DEN 1955-09-06
17   István RÓZSAVÖLGYI  220.60     HUN 1956-08-03
16        Olavi SALSOLA  220.20     FIN 1957-07-11
15        Olavi SALONEN  220.20     FIN 1957-07-11
14  Stanislav JUNGWIRTH  218.10     TCH 1957-07-12
13         Herb ELLIOTT  216.00     AUS 1958-08-28
12         Herb ELLIOTT  215.60     AUS 1960-09-06
11             Jim RYUN  213.10     USA 1967-07-08
10         Filbert BAYI  212.20     TAN 1974-02-02
9         Sebastian COE  212.10     GBR 1979-08-15
8           Steve OVETT  212.10     GBR 1980-07-15
7           Steve OVETT  211.36     GBR 1980-08-27
6          Sydney MAREE  211.24     USA 1983-08-28
5           Steve OVETT  210.77     GBR 1983-09-04
4            Steve CRAM  209.67     GBR 1985-07-16
3           Saïd AOUITA  209.46     MAR 1985-08-23
2    Noureddine MORCELI  208.86     ALG 1992-09-06
1    Noureddine MORCELI  207.37     ALG 1995-07-12
0    Hicham EL GUERROUJ  206.00     MAR 1998-07-14

In [32]:
new_df = df[["Mark", "date"]]
new_df["year"] = new_df["date"].apply(lambda x: x.year)
new_df = new_df[["Mark", "year"]]
new_df = new_df.sort_values(by='year', ascending=True)
new_df["year"] = new_df["year"] - 1896

/var/folders/r4/sgr1zrxx0038xwsxj6n3k8900000gn/T/ipykernel_95941/409202202.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["year"] = new_df["date"].apply(lambda x: x.year)

In [33]:
new_df.to_csv("by_year.csv", index=False)